### ISSUE TITLE
The Short-Bio of the Mentors needs to be displayed again.

### ISSUE THREAD

**Issue by Roritharr** [foundershub/StartupWeekendBundle#1]
Currently the Short-Bios of the Mentors aren't visible. That needs to be changed to work similar as with the Judges.

**Comment by coderbyheart** [comment]
![screenshot52](https://cloud.githubusercontent.com/assets/188915/9068848/1d91addc-3ae6-11e5-9eff-2c47cbeb34b0.png)

The short bios are way too long.

They need to be shorter than 200 characters or 25 words.
