### ISSUE TITLE
Add Blog-Section

### ISSUE THREAD

**Issue by Roritharr** [foundershub/StartupWeekendBundle#8]
Anne needs a Blog-Roll Section where she can publish short articles that are direct linkable (via hash urls)

**Comment by coderbyheart** [comment]
When will we have the first blog post ready?

**Comment by coderbyheart** [comment]
The news / blog section can now be seen on https://preview.startupweekendrheinmain.de/#news

They are fed by the new content type `Blog entry` in contentful.

**Comment by coderbyheart** [comment]
Once you have you first blog post ready I will update live.
